Removed trailing slash that completely broke Windows installations
This was causing both setuptools and distribute to fail with
"AttributeError: NoneType has no attribute 'close'".